export class Ship {
    public id: number;
    public name?: string;
    public faction?: string;
    public frontExtreme?: number;
    public frontLong?: number;
    public frontMed?: number;
    public frontShort?: number;
    public sideExtreme?: number;S
    public sideLong?: number;
    public sideMed?: number;
    public sideShort?: number;
    public rearExtreme?: number;
    public rearLong?: number;
    public rearMed?: number;
    public rearShort?: number;
    public hullPoints?: number;
    public shieldFront?: number;
    public shieldSide?: number;
    public shieldRear?: number;
    public defenseId1?: number;
    public defenseId2?: number;
    public defenseId3?: number;
    public defenseId4?: number;
    public defenseId5?: number;
    public defenseId6?: number;
    public defenseId7?: number;
    public maxSpeed?: number;
    public command?: number;
    public squadron?: number;
    public engineering?: number;
    public maxTurn1?: number;
    public maxTurn2?: number;
    public maxTurn3?: number;
    public maxTurn4?: number;
    public antiSquadron?: number;
    public cost?: number;

}