import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CharacterdataService {

  getCharacterData() {
    return {
      condition: '1',
      headers:  [
        {name: 'Name', value: '', width: 'width-7'},
        {name: 'Player', value: '', width: 'width-5'},
        {name: 'Classes', value: '', width: 'width-10'},
        {name: 'Level', value: '', width: 'width-2'},
        {name: 'Species', value: '', width: 'width-4'},
        {name: 'Sex', value: '', width: 'width-2'},
        {name: 'Age', value: '', width: 'width-2'},
        {name: 'Height', value: '', width: 'width-2'},
        {name: 'Weight', value: '', width: 'width-2'},
        {name: 'Destiny', value: '', width: 'width-10'},
        {name: 'XP', value: '', width: 'width-2'},
      ],
      stats: [
        {name: 'Strength', value: '', width: 'width-1', readOnly:true},
        {name: 'Score', value: '', width: 'width-1'},
        {name: 'Mod', value: '', width: 'width-1'},
        {name: '', value: '', width: 'width-3 hidden', readOnly:true},
        {name: 'Total HP', value: '', width: 'width-3'},
        {name: 'Current HP', value: '', width: 'width-3'},
        {name: 'Dexterity', value: '', width: 'width-1', readOnly:true},
        {name: 'Score', value: '', width: 'width-1'},
        {name: 'Mod', value: '', width: 'width-1'},
        {name: '', value: '', width: 'width-2 hidden', readOnly:true},
        {name: 'Damage Threshold', value: '', width: 'width-3', readOnly:true},
        {name: 'Fort', value: '', width: 'width-2'},
        {name: 'Misc', value: '', width: 'width-2'},
        {name: 'Constitution', value: '', width: 'width-1', readOnly:true},
        {name: 'Score', value: '', width: 'width-1'},
        {name: 'Mod', value: '', width: 'width-1'},
        {name: '', value: '', width: 'width-3 hidden', readOnly:true},
        {name: 'Damage Reduction', value: '', width: 'width-3', readOnly:true},
        {name: 'Sheild', value: '', width: 'width-3'},
        {name: 'Intelligence', value: '', width: 'width-1', readOnly:true},
        {name: 'Score', value: '', width: 'width-1'},
        {name: 'Mod', value: '', width: 'width-1'},
        {name: '', value: '', width: 'width-3 hidden', readOnly:true},
        {name: 'Base Attack', value: '', width: 'width-3', readOnly:true},
        {name: 'Speed', value: '', width: 'width-3'},
        {name: 'Wisdom', value: '', width: 'width-1', readOnly:true},
        {name: 'Score', value: '', width: 'width-1'},
        {name: 'Mod', value: '', width: 'width-1'},
        {name: '', value: '', width: 'width-3 hidden', readOnly:true},
        {name: 'Force Points', value: '', width: 'width-3', readOnly:true},
        {name: 'Destiny Points', value: '', width: 'width-3'},
        {name: 'Charisma', value: '', width: 'width-1', readOnly:true},
        {name: 'Score', value: '', width: 'width-1'},
        {name: 'Mod', value: '', width: 'width-1'},
        {name: '', value: '', width: 'width-3 hidden', readOnly:true},
        {name: 'Credits', value: '', width: 'width-3'},
        {name: 'Dark Side Points', value: '', width: 'width-3'},
      ],
      defense: [
        {name: 'Fortification', value: '', width: 'width-2', readOnly:true},
        {name: '', value: '10', width: 'width-2', readOnly:true},
        {name: 'Level/Armor', value: '', width: 'width-2'}, 
        {name: 'Consitution', value: '', width: 'width-2', readOnly:true}, 
        {name: 'Class', value: '', width: 'width-2'}, 
        {name: 'Misc', value: '', width: 'width-2'}, 
        {name: 'Reflex', value: '', width: 'width-2', readOnly:true},
        {name: '', value: '10', width: 'width-2', readOnly:true},
        {name: 'Level/Armor', value: '', width: 'width-2'}, 
        {name: 'Dexterity', value: '', width: 'width-2', readOnly:true}, 
        {name: 'Class', value: '', width: 'width-2'}, 
        {name: 'Misc', value: '', width: 'width-2'},
        {name: 'Will', value: '', width: 'width-2', readOnly:true},
        {name: '', value: '10', width: 'width-2', readOnly:true},
        {name: 'Level/Armor', value: '', width: 'width-2'}, 
        {name: 'Wisdom', value: '', width: 'width-2', readOnly:true}, 
        {name: 'Class', value: '', width: 'width-2'}, 
        {name: 'Misc', value: '', width: 'width-2'},
      ],
      skills:[
          {name: 'Acrobatics', value: '', width: 'width-4', readOnly:true, attr: 'dex'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Climb', value: '', width: 'width-4', readOnly:true, attr: 'str'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Deception', value: '', width: 'width-4', readOnly:true, attr: 'cha'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Endurance', value: '', width: 'width-4', readOnly:true, attr: 'con'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Gather Information', value: '', width: 'width-4', readOnly:true, attr: 'cha'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Initiative', value: '', width: 'width-4', readOnly:true, attr: 'dex'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Jump', value: '', width: 'width-4', readOnly:true, attr: 'str'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Knowledge: Bureaucracy', value: '', width: 'width-4', readOnly:true , attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Knowledge: Gal Lore', value: '', width: 'width-4', readOnly:true, attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Knowledge: Life Sci', value: '', width: 'width-4', readOnly:true, attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Knowledge: Ph. Sci.', value: '', width: 'width-4', readOnly:true, attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Knowledge: Soc. Sci.', value: '', width: 'width-4', readOnly:true, attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Knowledge: Tactics', value: '', width: 'width-4', readOnly:true, attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Knowledge: Techn', value: '', width: 'width-4', readOnly:true, attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Mechanics', value: '', width: 'width-4', readOnly:true, attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Perception', value: '', width: 'width-4', readOnly:true, attr: 'wis'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Persuasion', value: '', width: 'width-4', readOnly:true, attr: 'cha'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Pilot', value: '', width: 'width-4', readOnly:true, attr: 'dex'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Ride', value: '', width: 'width-4', readOnly:true, attr: 'dex'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Stealth', value: '', width: 'width-4', readOnly:true, attr: 'dex'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Survival', value: '', width: 'width-4', readOnly:true, attr: 'wis'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Swim', value: '', width: 'width-4', readOnly:true, attr: 'str'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Treat Injury', value: '', width: 'width-4', readOnly:true, attr: 'wis'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Use Computer', value: '', width: 'width-4', readOnly:true, attr: 'int'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
          {name: 'Use The Force', value: '', width: 'width-4', readOnly:true, attr: 'cha'},
          {name: 'Train', value: '', width: 'width-2'}, 
          {name: 'Focus', value: '', width: 'width-2'},
          {name: 'Misc', value: '', width: 'width-2'},
          {name: 'Armor', value: '', width: 'width-2'},
      ],
      armor: [
          {name: 'Armor', value: '', width: 'width-4'},
          {name: 'Speed', value: '', width: 'width-2'}, 
          {name: 'Ref Def', value: '', width: 'width-2'},
          {name: 'Fort Def', value: '', width: 'width-2'},
          {name: 'Max. Dex', value: '', width: 'width-2'},
      ],
      weapons: [
      ],
      talents: [
      ],
      feats: [
      ],
      languages: [
      ],
      species: [
      ],
      equipment: [
      ],
      force: [
      ],
      actions:[]
    }
  }
}
